"""Stage implementations (M3: the real deterministic spine).

Every stage decides "done?" by files and fails with ONE actionable
reason. Manual-first: any human-provided artifact makes its stage skip.
LLM agents (script/planner) arrive in M4 — until then both have
deterministic fallbacks so the pipeline runs end to end at $0.
"""

from __future__ import annotations

import json
import re
import subprocess

from ..compiler import compile_plan
from ..context import StageContext
from ..costs import budget_gate
from ..errors import StageError
from ..media import extract_audio, probe_duration, run_ffmpeg
from ..providers import tts, whisper
from ..srt import SrtItem, read_srt, write_srt
from ..textsplit import split_sentences
from ..validators import validate_beat_sheet, validate_plan

# ---------------- script ----------------


def run_script(ctx: StageContext) -> None:
    title = str(ctx.video.get("title") or "").strip()
    if not title:
        raise StageError("script", "video has no title and no script.txt was provided")
    generator = str(((ctx.cfg.get("script") or {}).get("generator")) or "simple")
    llm = str(((ctx.cfg.get("script") or {}).get("llm")) or "mock")
    if llm not in ("mock",):
        # real LLM script agents land in M4
        raise StageError(
            "script",
            f"script llm '{llm}' not available yet (M4) — upload script.txt or set script.llm to 'mock'",
        )
    # deterministic 'simple' generator: an honest, structured placeholder narration
    sentences = [
        f"{title}.",
        f"This video explores {title.lower().rstrip('.')} in three short parts.",
        "First, the background that made it possible.",
        "Then, the turning point that changed everything.",
        "Finally, what it left behind, and why it still matters today.",
    ]
    ctx.artifact("script.txt").write_text(" ".join(sentences) + "\n", encoding="utf-8")
    ctx.log(f"script generated by '{generator}' (mock llm)")


# ---------------- narration ----------------


def run_narration(ctx: StageContext) -> None:
    if ctx.has("avatar.mp4") and not ctx.has("audio.mp3"):
        extract_audio("narration", ctx.artifact("avatar.mp4"), ctx.artifact("audio.mp3"))
        ctx.log("audio extracted from uploaded avatar video")
        return
    script = ctx.artifact("script.txt").read_text(encoding="utf-8").strip()
    tts.synthesize(ctx, script)
    ctx.log("narration synthesized")


# ---------------- transcript ----------------


def run_transcript(ctx: StageContext) -> None:
    if ctx.has("tts_timings.json"):
        timings = ctx.read_json("tts_timings.json")["items"]
        write_srt(
            ctx.artifact("subtitles.srt"),
            [SrtItem(t["start_s"], t["end_s"], t["text"]) for t in timings],
        )
        ctx.log("subtitles built from TTS adapter timings")
        return
    whisper.transcribe(ctx, ctx.artifact("audio.mp3"))
    ctx.log("subtitles transcribed by local whisper")


# ---------------- plan_beats ----------------


def run_plan_beats(ctx: StageContext) -> None:
    llm = str(((ctx.cfg.get("planner") or {}).get("llm")) or "mock")
    script = ctx.artifact("script.txt").read_text(encoding="utf-8").strip()
    audio_duration = probe_duration("plan_beats", ctx.artifact("audio.mp3"))

    if llm != "mock":
        raise StageError(
            "plan_beats",
            f"planner llm '{llm}' not available yet (M4) — upload beats.json or set planner.llm to 'mock'",
        )

    beats_doc = _fallback_planner(ctx, script)
    violations = validate_beat_sheet(beats_doc, script, ctx.cfg, audio_duration)
    if violations:
        raise StageError(
            "plan_beats",
            "generated beat sheet failed validation: " + "; ".join(violations[:8]),
        )
    ctx.write_json("beats.json", beats_doc)
    ctx.log(f"beat sheet planned ({len(beats_doc['beats'])} beats, deterministic fallback planner)")


_STOPWORDS = set(
    "the a an and or of in on at to for with by from is are was were be this that it its as into over under".split()
)


def _fallback_planner(ctx: StageContext, script: str) -> dict:
    """Deterministic no-LLM planner: one beat per 1–2 sentences, visual
    intent derived from the sentence's content words. The manual fallback
    for every AI failure (D2) — and the M3 default."""
    sentences = split_sentences(script)
    style = ctx.cfg.get("style_pack_doc") or {}
    avg_hold = float((style.get("pacing") or {}).get("avg_hold_seconds", 4.0))
    per_beat = 1 if avg_hold <= 4.0 else 2

    beats = []
    for i in range(0, len(sentences), per_beat):
        chunk = sentences[i : i + per_beat]
        words = [
            w.lower().strip(".,!?…:;\"'")
            for w in " ".join(chunk).split()
            if w.lower().strip(".,!?…:;\"'") not in _STOPWORDS
        ]
        subject = " ".join(words[:8]) or "establishing shot"
        visual = str(style.get("visual_language") or "").strip()
        intent = f"{subject}, wide establishing shot" + (f", {visual.rstrip('.').lower()}" if visual else "")
        beats.append(
            {
                "id": f"b{i // per_beat + 1}",
                "kind": "narration",
                "script_text": " ".join(chunk),
                "visual_intent": intent[:300],
                "mood": "neutral",
                "media_preference": "any",
            }
        )
    return {"version": "1.0", "video_id": ctx.video_id, "beats": beats}


# ---------------- compile_plan ----------------


def _sentence_timings(ctx: StageContext) -> list[dict]:
    if ctx.has("tts_timings.json"):
        return ctx.read_json("tts_timings.json")["items"]
    return [
        {"text": s.text, "start_s": s.start_s, "end_s": s.end_s}
        for s in read_srt(ctx.artifact("subtitles.srt"))
    ]


def run_compile_plan(ctx: StageContext) -> None:
    beats_doc = ctx.read_json("beats.json")
    audio_duration = probe_duration("compile_plan", ctx.artifact("audio.mp3"))

    # human-provided beats are validated here (agent-produced ones were already)
    script = ctx.artifact("script.txt").read_text(encoding="utf-8").strip() if ctx.has("script.txt") else ""
    if script:
        violations = validate_beat_sheet(beats_doc, script, ctx.cfg, audio_duration)
        if violations:
            raise StageError("compile_plan", "beats.json invalid: " + "; ".join(violations[:8]))

    plan = compile_plan(beats_doc, _sentence_timings(ctx), ctx.cfg, audio_duration)
    structural = validate_plan(plan, ctx.folder, ctx.cfg, audio_duration, require_assets=False)
    if structural:
        raise StageError(
            "compile_plan",
            "compiler produced an invalid plan (bug): " + "; ".join(structural[:8]),
        )
    ctx.write_json("edit_plan.json", plan)
    ctx.log(f"plan compiled: {len(plan['tracks']['visual'])} visual items, "
            f"{len(plan['tracks']['overlays'])} overlays")


# ---------------- resolve_assets ----------------


def assets_resolved(ctx: StageContext) -> bool:
    if not ctx.has("edit_plan.json"):
        return False
    try:
        plan = ctx.read_json("edit_plan.json")
    except StageError:
        return False
    for item in plan["tracks"]["visual"]:
        path = str(item["asset"].get("path", ""))
        if not path or not (ctx.folder / path).exists():
            return False
    return True


def run_resolve_assets(ctx: StageContext) -> None:
    plan = ctx.read_json("edit_plan.json")
    beats = {b["id"]: b for b in ctx.read_json("beats.json")["beats"]} if ctx.has("beats.json") else {}
    chain = ((ctx.cfg.get("source_policy") or {}).get("visual") or {}).get("chain") or []
    if not chain:
        raise StageError("resolve_assets", "source_policy.visual.chain is empty — nothing can be sourced")

    (ctx.folder / "clips").mkdir(exist_ok=True)
    changed = False
    for item in plan["tracks"]["visual"]:
        path = str(item["asset"].get("path", ""))
        if path and (ctx.folder / path).exists():
            continue  # human-provided or already resolved
        beat = beats.get(str(item.get("beat_id")))
        query = str((beat or {}).get("visual_intent") or ctx.video.get("title") or "establishing shot")
        resolved = _resolve_one(ctx, item, query, chain)
        if not resolved:
            raise StageError(
                "resolve_assets",
                f"source chain exhausted for beat {item.get('beat_id')} (item {item['id']}) — "
                f"query was: {query!r}; add sources, lower min_score, or edit the beat",
            )
        changed = True

    if changed:
        ctx.write_json("edit_plan.json", plan)
    ctx.log("assets resolved for all visual items")


def _resolve_one(ctx: StageContext, item: dict, query: str, chain: list[dict]) -> bool:
    for source in chain:
        kind = source.get("source")
        if kind == "library":
            # M5: real library adapter. Until vendored, record and fall through.
            ctx.db.provider_health("library", False, "library service not vendored yet (M5)")
            continue
        if kind == "stock":
            ctx.db.provider_health("stock.pexels", False, "stock adapter arrives in M5")
            continue
        if kind == "ai_image":
            provider = str(source.get("provider") or "mock")
            if provider != "mock":
                ctx.db.provider_health(f"ai_image.{provider}", False, "only 'mock' ai_image exists before M5")
                continue
            _mock_image(ctx, item, query, str(source.get("style") or ""))
            ctx.db.asset_usage(ctx.video_id, str(item.get("beat_id") or ""), "ai", None, "owned", "mock")
            ctx.db.provider_health("ai_image.mock", True)
            return True
    return False


def _mock_image(ctx: StageContext, item: dict, query: str, style: str) -> None:
    """$0 'generation': a styled slate carrying the visual intent text —
    an honest stand-in until M5 wires real sources."""
    with budget_gate(
        ctx, stage="resolve_assets", provider="mock", operation="image.generate",
        estimated_units=1, details={"query": query[:120]},
    ):
        out_rel = f"clips/{item['id']}.jpg"
        out = ctx.folder / out_rel
        text = re.sub(r"[^\w\s,.-]", "", query)[:90]
        wrapped = "\n".join(text[i : i + 45] for i in range(0, len(text), 45))
        res = ctx.cfg.get("output") or {}
        w, h = int(res.get("width", 1920)), int(res.get("height", 1080))
        run_ffmpeg("resolve_assets", [
            "-f", "lavfi",
            "-i", f"color=c=0x14161c:s={w}x{h}",
            "-vf",
            (
                "drawbox=x=0:y=ih*0.42:w=iw:h=ih*0.16:color=0x000000@0.35:t=fill,"
                f"drawtext=font='DejaVu Sans':fontsize={h // 22}:fontcolor=0xcbd2e0:"
                f"x=(w-text_w)/2:y=(h-text_h)/2:text='{_esc(wrapped)}'"
            ),
            "-frames:v", "1", "-q:v", "3", str(out),
        ])
        item["media_type"] = "image"
        item["asset"] = {
            "source": "ai", "provider": "mock", "id": None, "license": "owned",
            "path": out_rel, "score": None, "query": query[:200],
        }
        item.setdefault("motion", {"type": "ken_burns", "direction": "in", "pan": "center", "strength": 0.12})


def _esc(text: str) -> str:
    return text.replace("\\", "").replace("'", "").replace(":", "\\:").replace("%", "\\%")


# ---------------- validate (full, always runs) ----------------


def run_validate(ctx: StageContext) -> None:
    plan = ctx.read_json("edit_plan.json")
    audio_duration = probe_duration("validate", ctx.artifact("audio.mp3")) if ctx.has("audio.mp3") else None
    violations = validate_plan(plan, ctx.folder, ctx.cfg, audio_duration, require_assets=True)
    if violations:
        raise StageError("validate", f"{len(violations)} violation(s): " + "; ".join(violations[:10]))
    ctx.log("full validation passed")


# ---------------- render ----------------


def run_render(ctx: StageContext) -> None:
    renderer = str(ctx.cfg.get("renderer") or "auto")
    cli = ctx.config.engine_cli
    if not cli.exists():
        raise StageError("render", f"engine CLI not found at {cli} — set ENGINE_CLI")
    proc = subprocess.run(
        ["node", "--experimental-strip-types", str(cli),
         "render", "--video-dir", str(ctx.folder), "--renderer", renderer],
        capture_output=True, text=True, timeout=1800,
    )
    if proc.returncode != 0:
        reason = (proc.stderr or proc.stdout).strip().splitlines()
        raise StageError("render", f"engine failed: {reason[-1] if reason else 'no output'}")
    try:
        info = json.loads(proc.stdout.strip().splitlines()[-1])
        ctx.db.event(ctx.video_id, "render", "progress", f"renderer: {info.get('renderer')}")
        ctx.log(f"rendered via {info.get('renderer')} ({info.get('duration_s')}s)")
    except (json.JSONDecodeError, IndexError):
        ctx.log("rendered (engine reported no JSON summary)")


# ---------------- finalize ----------------


def run_finalize(ctx: StageContext) -> None:
    final = ctx.artifact("final.mp4")
    duration = probe_duration("finalize", final)
    run_ffmpeg("finalize", [
        "-ss", f"{min(1.0, duration / 2):.2f}", "-i", str(final),
        "-frames:v", "1", "-q:v", "3", str(ctx.artifact("thumb.jpg")),
    ])
    ctx.artifact("metadata.txt").write_text(
        f"title: {ctx.video.get('title')}\nchannel: {ctx.channel_id}\n"
        f"duration_s: {duration:.2f}\nvideo_id: {ctx.video_id}\n",
        encoding="utf-8",
    )
    ctx.db.set_size(ctx.video_id, final.stat().st_size)

    # retention (D19): clips/ deleted after render if configured
    retention = ctx.cfg.get("retention") or {}
    if str(retention.get("clips", "on_render")) == "on_render":
        clips = ctx.folder / "clips"
        if clips.is_dir():
            for f in clips.iterdir():
                f.unlink()
            clips.rmdir()
            ctx.log("retention: clips/ removed after render")
