#!/usr/bin/env node
/**
 * fonts/*.woff2 -> src/themes/fonts.generated.ts (D70).
 *
 * The render bundle has no public dir it can rely on — `remotion.config.ts`
 * points it at the fixture video-dir and the CLI render path overrides it per
 * render — so a packaged font cannot be a `staticFile()`. It has to be inlined,
 * and 115 KB of woff2 is cheap enough to inline that this is not a compromise.
 *
 * Run after adding or replacing a file in fonts/. The output is committed;
 * `engine/test/fonts.test.ts` fails if it drifts from the directory.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const engineRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(engineRoot, "fonts");
const out = join(engineRoot, "src/themes/fonts.generated.ts");

/**
 * A file called `PlayfairDisplay.woff2` has to become the CSS family
 * `Playfair Display`, because that is the string a theme writes and the string
 * `fontStack()` quotes. Split on the camel humps.
 */
const familyOf = (file) =>
  basename(file, ".woff2")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .trim();

/**
 * The weight axis each variable file actually carries. A `font-weight` range
 * narrower than the file is a silent downgrade (the browser synthesises the
 * rest); wider is worse (it clamps and you never see it).
 */
const WEIGHT_RANGE = {
  Inter: "300 900",
  "Playfair Display": "400 900",
  Oswald: "200 700",
};

const files = readdirSync(fontsDir)
  .filter((f) => f.endsWith(".woff2"))
  .sort();
if (files.length === 0) {
  console.error("no .woff2 files in engine/fonts");
  process.exit(1);
}

const faces = files.map((file) => {
  const family = familyOf(file);
  const range = WEIGHT_RANGE[family];
  if (!range) {
    console.error(`no weight range declared for "${family}" — add one to pack-fonts.mjs`);
    process.exit(1);
  }
  const b64 = readFileSync(join(fontsDir, file)).toString("base64");
  return { family, range, b64, file };
});

const css = faces
  .map(
    (f) =>
      `@font-face{font-family:'${f.family}';font-style:normal;` +
      `font-weight:${f.range};font-display:block;` +
      `src:url(data:font/woff2;base64,${f.b64}) format('woff2')}`
  )
  .join("\n");

const body = `/**
 * GENERATED by scripts/pack-fonts.mjs — do not edit.
 *
 * The @font-face block every render tree mounts, with each family's latin
 * subset inlined as a data URI. See fonts/README.md.
 *
 * Sources: ${faces.map((f) => f.file).join(", ")}
 */

/** Families this bundle actually carries, in the order they are declared. */
export const PACKAGED_FAMILIES = [
${faces.map((f) => `  ${JSON.stringify(f.family)},`).join("\n")}
] as const;

export const FONT_FACE_CSS = ${JSON.stringify(css)};
`;

writeFileSync(out, body);
console.log(
  `packed ${faces.length} families (${faces.map((f) => f.family).join(", ")}) -> ${(
    body.length / 1024
  ).toFixed(0)} KB`
);
