/**
 * The single seam every catalog component imports: the Theme type plus the
 * theme runtime helpers. Components stay portable (one relative import, no
 * knowledge of where contracts or the runtime live) and appearance keeps
 * resolving in exactly one place — engine/src/themes/runtime.ts (D8).
 */
export type { Entrance, Theme } from "@lusora/contracts";
export {
  DEFAULT_THEME,
  accentInk,
  blend,
  borderSides,
  capsTracking,
  captionStyle,
  chartStyle,
  chipColor,
  countedValue,
  composition,
  contrastInk,
  contrastRatio,
  densityScale,
  easingCurve,
  elevationShadow,
  emphasisColor,
  entranceFor,
  fadeInOutRange,
  figureFrame,
  figureFace,
  fontStack,
  fullBleed,
  groundStyle,
  labelFace,
  markStyle,
  motionScale,
  mutedInk,
  pageGround,
  paperStock,
  photoMat,
  plateColor,
  posterPad,
  rowIndex,
  ruleWidth,
  seriesColors,
  surfaceColor,
  surfaceStyle,
  textPlate,
  textureLayer,
  titleChips,
  titleOnShot,
  titleRule,
  typeCase,
  typeScale,
  typeTracking,
  typeWeight,
  verdictColors,
  type AccentRule,
  type CaptionStyle,
  type ChartBase,
  type ChartStyle,
  type Composition,
  type SurfaceStyle,
  type TextPlating,
  type TypeRole,
} from "../themes/runtime.ts";
export {
  PANEL_ENTRANCES,
  TEXT_ENTRANCES,
  useEntrance,
  type EntranceState,
} from "../themes/entrance.ts";
